//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncludingDemo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class IncludingDemo : global::System.Configuration.ApplicationSettingsBase {
        
        private static IncludingDemo defaultInstance = ((IncludingDemo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IncludingDemo())));
        
        public static IncludingDemo Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ATG\\demo20130923\\demo.exe")]
        public string SubAppPath
        {
            get
            {
                return ((string)(this["SubAppPath"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bul")]
        public string TitleStringList
        {
            get
            {
                return ((string)(this["TitleStringList"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5, -25")]
        public global::System.Drawing.Point Frame3DLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["Frame3DLocation"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FrameMidLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["FrameMidLocation"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Frame3DSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["Frame3DSize"]));
            }
        }
    }
}
